language: ruby
rvm:
- 2.0.0
deploy:
  provider: rubygems
  api_key:
    secure: b2DxgLbIDryhuaaTqnph9b15Yhh4ZNfOsiL6AqO2Cb4rlr+IUnrcR8+aQyhHlk2zKi/1FCIOTDKpp8mZOERkzN6EtGrvCLdDsN4ILdem0weVQCl/1xh/+JI6qWszg5jOdx7AXste6hzKR7Y+liIGaw5GkvuUlLA4oE5Yvb2Fgd9sNtiUjbwn0gVvxcHkfmlsmR2p/mHjKmqYNfx1ycMfdRrzzehhW6p8p5h57uVjI/m+YAM05OUyrJVTPLwdNteE+lbs7gCBDEq1EVBup7e4H0XKaz1+9jCSRCvZLkjNMcpbXImth2N65VFbNLr59tHjj9Y56n9GOTdOH9HQPXoFV9a6eZ9E3oI0ZXvRyjeWJsRRzE6K6zEHGH8lSXSi/Vfa1uiXhFLTggVC2t5jl3SFk+dEh5koKz7DPlqxijinIWjEQGBtTxaRdAuXdbB+LY/mrjEJoPbtMj6ruFqh+fcwTrRfGgyQxYSATC3PizJrTrpZDNeTWET0QukZPjEnkPWB3WWWezwz4OgCT5pGt8aXs2wtvN604vuNJR9XtgPIlm9asf7Jj5V23GA71LU1SnedAxjfqIV16x3dm4O8eNzYRy+pai0BvlWO57UaSRHwqIYcqxM50KPr8rdLEKusPJha5Ysywc06XCsrG10nPyEWnRYhHxscZVXsQyqWHKjF7AU=
  gem: cookbook-release
  on:
    tags: true
    repo: criteo/cookbook-release
